# Generated by Django 5.1.1 on 2024-10-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='candidate_id',
            field=models.IntegerField(blank=True, db_column='candidate_id', null=True),
        ),
    ]
