# Generated by Django 5.1.1 on 2024-09-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_user_created_at_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
