# Generated by Django 5.1.1 on 2024-10-03 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_candidate_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='speech',
            field=models.TextField(),
        ),
    ]
