# Generated by Django 5.1.1 on 2024-10-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='speech',
            field=models.TextField(unique=True),
        ),
    ]
