# Generated by Django 5.1.1 on 2024-10-08 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_candidate_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 0, 30, 35, 402469, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='election',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 0, 30, 35, 402469, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('registered', 'NOT_STARTED'), ('in_voting', 'IN_PROGRESS'), ('closed ', 'COMPLETED')], default='registered', max_length=20),
        ),
    ]
