# Generated by Django 5.1.1 on 2024-10-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_election_end_date_alter_election_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='candidates',
        ),
        migrations.AddField(
            model_name='election',
            name='candidates',
            field=models.ManyToManyField(null=True, to='management.candidate'),
        ),
    ]
