# Generated by Django 5.1.1 on 2024-10-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED ', 'COMPLETED')], default='NOT_STARTED', max_length=20),
        ),
    ]
