# Generated by Django 5.1.1 on 2024-10-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
