# Generated by Django 5.1.1 on 2024-10-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='count_votes',
            field=models.IntegerField(default=0),
        ),
    ]
