# Generated by Django 5.1.1 on 2024-10-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_candidate_count_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_already_voted',
            field=models.BooleanField(default=False),
        ),
    ]
